### ISSUE TITLE
Whether this judgment will cause some files to be unpacked incorrect？

### ISSUE THREAD

**Issue by N1neSun** [doomedraven/sflock#18]
https://github.com/doomedraven/sflock/blob/98962eab780e42956c58d2b1f72358ea9bcf1f67/sflock/pick.py#L73
Should we judge all `magic` before using `endswith`?

**Comment by doomedraven** [comment]
hello, could be an option yes, but magic sometime is even more confusing, could you provide a case/hash to check?

**Comment by N1neSun** [comment]
[1.docx](https://github.com/doomedraven/sflock/files/7816123/1.docx)
This case is actually in eml format, but unpack is unsuccessful

**Comment by doomedraven** [comment]
ok i see what do you mean, im totally fine to improve that but if you can make PR that would be amazing, as i just returned from vacations and have a lot of stuff to handle so it will take some time to implement that by me

**Comment by N1neSun** [comment]
ok,i will try to implement it.
