### ISSUE TITLE
Identification for UDF Files

### ISSUE THREAD

**Issue by cccs-kevin** [doomedraven/sflock#25]
Hey there!

Can you please add identification for UDF files to the `identify()` method so that when it is called in CAPE [here](https://github.com/kevoreilly/CAPEv2/blob/master/lib/cuckoo/core/database.py#L1603) the `tmp_package` is `udf`?

Some samples of UDF files:
1. https://www.virustotal.com/gui/file/81343a9be0c301685f76fa2185dc8b28c0e8aebdca6f23ba12a4412685e286f6/details
2. https://www.virustotal.com/gui/file/dcf8b1e16e8f73752f96b8b3acc66670c595819aa23687c53dc0e314358d47b8
3. https://www.virustotal.com/gui/file/b9146bab2d7570fe4c48e9b7472d04a80af56a18ff9eab37df55146d0adcc10a

We are identifying UDF files in [Assemblyline](https://cyber.gc.ca/en/tools-services/assemblyline) with the following YARA rule https://github.com/CybercentreCanada/assemblyline-base/blob/f0d254126c64f73c57b1435f4f66471afdb58811/assemblyline/common/custom.yara#L872:L891, if that helps

**Comment by doomedraven** [comment]
hello, thanks in case you wanna test before i do release https://github.com/doomedraven/sflock/pull/26 already merged to master

**Comment by cccs-kevin** [comment]
Looks good to me!
